version: 2

updates:
  - package-ecosystem: pub
    directory: /dart_cli
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
