name: Quality Check
description: Run quality checks

runs:
  using: composite
  steps:
    - name: Format check
      shell: bash
      working-directory: dart_cli
      run: dart format -l 120 --set-exit-if-changed bin lib test

    - name: Static analysis
      shell: bash
      working-directory: dart_cli
      run: dart analyze --fatal-infos

    - name: Run tests with coverage
      shell: bash
      working-directory: dart_cli
      run: dart test --coverage=coverage/

    - name: Generate LCOV report
      shell: bash
      working-directory: dart_cli
      run: dart run coverage:format_coverage --lcov --in=coverage/ --out=coverage/lcov.info --report-on=lib

    - name: Generate HTML coverage report
      shell: bash
      working-directory: dart_cli
      run: dart run coverde --update-check disabled report --input coverage/lcov.info --output coverage/html

    - name: Package HTML coverage report
      shell: bash
      working-directory: dart_cli
      run: |
        rm -f coverage/coverage_html.zip
        cd coverage/html
        zip -rq ../coverage_html.zip .

    - name: Enforce coverage threshold
      shell: bash
      working-directory: dart_cli
      run: dart run coverde --update-check disabled check 80 --input coverage/lcov.info --file-coverage-log-level overview

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          dart_cli/coverage/lcov.info
          dart_cli/coverage/coverage_html.zip
        if-no-files-found: warn
        retention-days: 7
