import 'package:gfrm_dart/src/models/runtime_options.dart';

RuntimeOptions buildRuntimeOptions({
  String commandName = commandMigrate,
  String sourceProvider = 'github',
  String sourceUrl = 'https://github.com/acme/source',
  String sourceToken = 'src-token',
  String targetProvider = 'gitlab',
  String targetUrl = 'https://gitlab.com/acme/target',
  String targetToken = 'dst-token',
  String migrationOrder = 'github-to-gitlab',
  bool skipTagMigration = false,
  String fromTag = '',
  String toTag = '',
  bool dryRun = false,
  bool nonInteractive = true,
  String workdir = '',
  String logFile = '',
  bool loadSession = false,
  bool saveSession = false,
  bool resumeSession = false,
  String sessionFile = '',
  String sessionTokenMode = 'env',
  String sessionSourceTokenEnv = defaultSourceTokenEnv,
  String sessionTargetTokenEnv = defaultTargetTokenEnv,
  String settingsProfile = '',
  int downloadWorkers = 4,
  int releaseWorkers = 1,
  String checkpointFile = '',
  String tagsFile = '',
  bool noBanner = true,
  bool quiet = true,
  bool jsonOutput = false,
  bool progressBar = false,
  bool demoMode = false,
  int demoReleases = 5,
  double demoSleepSeconds = 1.0,
}) {
  return RuntimeOptions(
    commandName: commandName,
    sourceProvider: sourceProvider,
    sourceUrl: sourceUrl,
    sourceToken: sourceToken,
    targetProvider: targetProvider,
    targetUrl: targetUrl,
    targetToken: targetToken,
    migrationOrder: migrationOrder,
    skipTagMigration: skipTagMigration,
    fromTag: fromTag,
    toTag: toTag,
    dryRun: dryRun,
    nonInteractive: nonInteractive,
    workdir: workdir,
    logFile: logFile,
    loadSession: loadSession,
    saveSession: saveSession,
    resumeSession: resumeSession,
    sessionFile: sessionFile,
    sessionTokenMode: sessionTokenMode,
    sessionSourceTokenEnv: sessionSourceTokenEnv,
    sessionTargetTokenEnv: sessionTargetTokenEnv,
    settingsProfile: settingsProfile,
    downloadWorkers: downloadWorkers,
    releaseWorkers: releaseWorkers,
    checkpointFile: checkpointFile,
    tagsFile: tagsFile,
    noBanner: noBanner,
    quiet: quiet,
    jsonOutput: jsonOutput,
    progressBar: progressBar,
    demoMode: demoMode,
    demoReleases: demoReleases,
    demoSleepSeconds: demoSleepSeconds,
  );
}
