import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Start Here',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{ type: 'autogenerated', dirName: 'configuration' }],
    },
    {
      type: 'category',
      label: 'Commands',
      items: [{ type: 'autogenerated', dirName: 'commands' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Project',
      items: [{ type: 'autogenerated', dirName: 'project' }],
    },
  ],
};

export default sidebars;
